### ISSUE TITLE
support for file uploads ?

### ISSUE THREAD

**Issue by raresp** [wireload/Ratatosk#4]
Hi,

I have been experimenting with Ratatosk. Many thanks for your work.
What would your recommendation for handling file uploads?
Assuming I have an WLRemoteObject subclass what would be the best way to add a binary attachment to it ?

Thanks,
Rares

**Comment by aljungberg** [comment]
Sorry, didn't see this issue before. File uploads can't be made using an AJAX request without also having the HTML5 File API which is not generally available.

For now to upload files you'll probably want `FileUpload.j`. You can still use Ratatosk to handle the meta data surrounding the file.
